# Generated by Django 3.1 on 2020-08-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('system', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('castingtime', models.CharField(max_length=50)),
                ('range', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('cooldown', models.CharField(max_length=50)),
                ('schools', models.ManyToManyField(to='list.Schools')),
                ('tags', models.ManyToManyField(to='list.tag')),
            ],
        ),
    ]
