# Generated by Django 3.1 on 2020-08-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='component',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spells',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spells',
            name='materials',
            field=models.TextField(default=''),
        ),
    ]
