# Generated by Django 3.1 on 2020-08-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200814_0441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schools',
            new_name='school',
        ),
        migrations.RenameModel(
            old_name='Spells',
            new_name='spell',
        ),
    ]
