# Generated by Django 3.1 on 2020-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20200814_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='resource',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
