# Generated by Django 3.1 on 2020-08-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_spell_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='castingtime',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='cooldown',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.CharField(default='self', max_length=20),
        ),
    ]
