# Generated by Django 3.1 on 2020-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20200814_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='component',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='tags',
            field=models.ManyToManyField(blank=True, to='list.tag'),
        ),
    ]
